export const USER_LOADING= "USER_LOADING"
export const USER_REGISTER= "USER_REGISTER"
export const USER_LOGIN= "USER_LOGIN"
export const GET_AUTH_USER= "GET_AUTH_USER"
export const USER_LOGOUT= "USER_LOGOUT"

export const GET_USERS_LOAD= "GET_USERS_LOAD"
export const GET_USERS_SUCCESS= "GET_USERS_SUCCESS"
export const GET_USERS_FAIL= "GET_USERS_FAIL"

export const GET_USER= "GET_USER"
export const EDIT_USER= "GET_USER"

export const ADD_POST= "ADD_POST"
export const UPDATE_POST= "UPDATE_POST"
export const GET_POST= "GET_POST"

export const FOLLOW_UNFOLLOW_USER= "FOLLOW_UNFOLLOW_USER"
export const UNFOLLOW_USER= "UNFOLLOW_USER"

export const GET_POSTS_LOAD= "GET_POSTS_LOAD"
export const GET_POSTS_SUCCESS= "GET_POSTS_SUCCESS"
export const GET_POSTS_FAIL= "GET_POSTS_FAIL"

export const GET_MY_POSTS_SUCCESS= "GET_MY_POSTS_SUCCESS"

export const LIKE_POST_SUCCESS= "LIKE_POST_SUCCESS"
export const SAVE_POST_SUCCESS= "SAVE_POST_SUCCESS"

export const ADD_COMMENT= "ADD_COMMENT"

export const ADD_CHAT= "ADD_CHAT"

export const GET_BOOKMARKED_POSTS_SUCCESS= "GET_BOOKMARKED_POSTS_SUCCESS"

export const GET_FOLLOWING_POSTS_SUCCESS= "GET_FOLLOWING_POSTS_SUCCESS"
